Remove create package action

diff --git a/.github/workflows/dbm-pipeline.yml b/.github/workflows/dbm-pipeline.yml
--- a/.github/workflows/dbm-pipeline.yml
+++ b/.github/workflows/dbm-pipeline.yml
@@ -2,22 +2,25 @@ name: Deployment Workflow
 
 env:
   RUNNERS_OPTIONS: -c cookies=enabled
-  DBMprojectName: "BrdJiraGitHub"
+  DBMprojectName: "GithubCICD"
   DBMauthType: "DBmaestroAccount"
   DBMuserName: "su@dbmaestro.com"
-  DBMserver: "SER1:8017"
-  local_path: "./packages/packages"
-  agent_jar_parent_path: "./agentjar"
+  DBMauthToken: "xe1lwMC1tT5thurFSnjkoLNq2N32QPqY"
+  DBMserver: "localhost:8017"
+  packages_path: "./packages/"
+
+  agent_jar_parent_path: "./agentjar/"
   agent_jar_path: "./agentjar/DBmaestroAgent.jar"
-  new_state: ${{ github.event.client_payload.new_state_id}}
-  #workflowstates
-  READY_TO_REVIEW_STATUS_ID: '10004'
-  
+
+ 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - dev
+    inputs:
+      package_name:
+        description: "Package folder name where the scripts to be deployed are located"
+  #push:
+  #  branches:
+  #    - dev
 jobs:
   # Job executed for Package Precheck. 
   # Triggered when a pull request is merged into Dev branch 
@@ -31,15 +34,33 @@ jobs:
           
       - name: Get DBMaestroAgent.jar file
         # Obtains the DBMaestroAgent.jar from the repository
-        #uses: DBMaestroDev/dbm_github_actions/get-dbmagent-jar@v2
-        uses: sergioldbm/dbm-agent-jar-action@v2.0.2
+        uses: dbmaestrodev/dbm-github-actions/get-dbmagent-jar@latest
         with: 
-          version: "v24.1.0.11442"
+          version: "v23.4.2.11298"
           target_path: ${{ env.agent_jar_parent_path }} 
 
-      - name: Log Branch Name 
-        run: | 
-            BRANCH_NAME=$(git log -1 --pretty=format:'%s' | sed 's/^Merge branch //;s/ into.*//' | sed 's/origin\///')
-            echo "Merged branch name: $BRANCH_NAME"
+      - name: Create Package
+        run: |
+            PACKAGE_PATH="${{ env.packages_path }}${{ github.event.inputs.package_name }}/" 
+            echo "Package Path $PACKAGE_PATH"
+            java -jar "${{ env.agent_jar_path }}" -CreateManifestFile -PathToScriptsFolder "$PACKAGE_PATH" 
+            ZIP_PATH="${{ env.packages_path }}${{ inputs.package_name }}.tar" 
+            tar -cvf "$ZIP_PATH" -C "${{ env.packages_path }}" ${{ github.event.inputs.package_name }}
+            echo 'java -jar "${{ env.agent_jar_path }}" -Package -ProjectName "${{ env.DBMprojectName }}" -IgnoreScriptWarnings True -FilePath "${{ env.packages_path }}${{ github.event.inputs.package_name }}.tar" -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"'
+            java -jar "${{ env.agent_jar_path }}" -Package -ProjectName "${{ env.DBMprojectName }}" -IgnoreScriptWarnings True -FilePath "$ZIP_PATH" -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
 
-    
+      - name: Upgrade RS
+        shell: bash
+        run: |
+            set +e
+            output=$(java -jar "${{ env.agent_jar_path }}" -Upgrade -ProjectName ${{ env.DBMprojectName }} -EnvName "Release Source" -PackageName ${{ inputs.package_name }} -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}" 2>&1 )
+            exit_code=$?
+            echo "exit code:"
+            echo "$exit_code"
+            echo "complete output"
+            echo "$output"
+            filtered_output=$(echo "$output" | grep "Error executing")
+            echo "filtered output:"
+            echo "$filtered_output"
+
+
